[phases.install]
cmds = ["npm install --legacy-peer-deps", "npm install @rollup/rollup-linux-x64-gnu --save-optional"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -s -l $PORT"
