[phases.setup]
cmds = ["apt-get update && apt-get install -y git-lfs", "git lfs install", "git lfs pull"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
